# Generated by Django 6.0.3 on 2026-04-06 05:24

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_name', models.CharField(max_length=120)),
                ('email', models.EmailField(max_length=254)),
                ('phone', models.CharField(max_length=50)),
                ('project_type', models.CharField(choices=[('starter', 'Starter Website'), ('business', 'Business Website'), ('premium', 'Premium / E-commerce'), ('custom', 'Custom Tech Solution')], max_length=20)),
                ('message', models.TextField()),
                ('budget_range', models.CharField(blank=True, choices=[('under-30000', 'Under Ksh 30,000'), ('30000-65000', 'Ksh 30,000 - 65,000'), ('65000-120000', 'Ksh 65,000 - 120,000'), ('120000-plus', 'Ksh 120,000+'), ('not-sure', 'Not sure yet')], max_length=20)),
                ('timeline', models.CharField(blank=True, max_length=120)),
                ('referral_source', models.CharField(blank=True, choices=[('referral', 'Referral'), ('instagram', 'Instagram'), ('tiktok', 'TikTok'), ('google', 'Google'), ('other', 'Other')], max_length=20)),
                ('reference_file', models.FileField(blank=True, upload_to='project-requests/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
