# Generated by Django 6.0.3 on 2026-04-06 06:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutCapability',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutCard',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section', models.CharField(choices=[('mission', 'Mission'), ('vision', 'Vision'), ('what', 'What we do'), ('values', 'Why it matters')], max_length=20)),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['section', 'order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='AboutHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='About Bwire Global Tech', max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('lede', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutOwner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(default='Bilford Derick Bwire', max_length=120)),
                ('role', models.CharField(default='Founder and owner', max_length=120)),
                ('lede', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='AboutStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactChecklistItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=160)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ContactHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='Start Your Project', max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('lede', models.TextField()),
                ('success_message', models.TextField(default='Thanks for reaching out! We have received your project request and will get back to you within 24 hours.')),
            ],
        ),
        migrations.CreateModel(
            name='ContactNextStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_label', models.CharField(default='01', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DeliverableItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeCaseStudy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('stat_primary', models.CharField(blank=True, max_length=60)),
                ('stat_secondary', models.CharField(blank=True, max_length=60)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeCta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Get started', max_length=120)),
                ('title', models.CharField(default='Send a website brief or an AI idea.', max_length=200)),
                ('body', models.TextField(default='We will turn it into a real project path, not generic filler.')),
                ('button_label', models.CharField(default='Open contact page', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='HomeFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='The Mind Behind the Machine', max_length=120)),
                ('title', models.CharField(default='We build websites first, then AI solutions that support the business.', max_length=200)),
                ('lede', models.TextField(default='Bwire Global Tech focuses on web development, then AI solutions, with added support for dashboards, cloud setup, and design where needed. The website should reflect real work, not generic filler.')),
                ('primary_cta_label', models.CharField(default='Start a project', max_length=60)),
                ('secondary_cta_label', models.CharField(default='See the vision', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='HomeMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeService',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='HomeTestimonial',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quote', models.TextField()),
                ('author', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioDeepDive',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('challenge', models.TextField()),
                ('approach', models.TextField()),
                ('result', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioDeepDiveMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='Portfolio', max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('lede', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='PortfolioItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(default='Case study', max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('body', models.TextField()),
                ('bullet_1', models.CharField(blank=True, max_length=120)),
                ('bullet_2', models.CharField(blank=True, max_length=120)),
                ('bullet_3', models.CharField(blank=True, max_length=120)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PortfolioOutcome',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=60)),
                ('label', models.CharField(max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingAddon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=80)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingCta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('eyebrow', models.CharField(default='Ready to build something powerful?', max_length=120)),
                ('title', models.CharField(default='Start your project or request a quote.', max_length=200)),
                ('primary_label', models.CharField(default='Start Your Project', max_length=80)),
                ('secondary_label', models.CharField(default='Request a Quote', max_length=80)),
            ],
        ),
        migrations.CreateModel(
            name='PricingHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='Pricing', max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('lede', models.TextField()),
                ('ai_note', models.TextField(default='AI solutions: From $700 per project. Custom AI systems are priced by scope.')),
            ],
        ),
        migrations.CreateModel(
            name='PricingPackage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=120)),
                ('price', models.CharField(max_length=80)),
                ('subtitle', models.CharField(blank=True, max_length=140)),
                ('bullet_1', models.CharField(blank=True, max_length=160)),
                ('bullet_2', models.CharField(blank=True, max_length=160)),
                ('bullet_3', models.CharField(blank=True, max_length=160)),
                ('bullet_4', models.CharField(blank=True, max_length=160)),
                ('bullet_5', models.CharField(blank=True, max_length=160)),
                ('bullet_6', models.CharField(blank=True, max_length=160)),
                ('footer_note', models.CharField(blank=True, max_length=160)),
                ('featured', models.BooleanField(default=False)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='PricingTerms',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('line_one', models.CharField(max_length=200)),
                ('line_two', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=140)),
                ('body', models.TextField()),
                ('bullet_1', models.CharField(blank=True, max_length=120)),
                ('bullet_2', models.CharField(blank=True, max_length=120)),
                ('bullet_3', models.CharField(blank=True, max_length=120)),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesFaq',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=200)),
                ('answer', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ServicesHero',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('badge', models.CharField(default='Services', max_length=120)),
                ('title', models.CharField(max_length=200)),
                ('lede', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('site_name', models.CharField(default='Bwire Global Tech', max_length=120)),
                ('tagline', models.CharField(default='The Mind Behind the Machine', max_length=120)),
                ('owner_name', models.CharField(default='Bilford Derick Bwire', max_length=120)),
                ('email', models.EmailField(default='bwireglobaltech917@gmail.com', max_length=254)),
                ('phone', models.CharField(default='0722206805', max_length=40)),
                ('instagram', models.CharField(default='bwireglobaltech', max_length=120)),
                ('tiktok', models.CharField(default='bwireglobaltech', max_length=120)),
                ('whatsapp_number', models.CharField(default='254722206805', max_length=20)),
                ('whatsapp_message', models.CharField(default="Hi Bwire Global Tech, I'd like to start a project.", max_length=240)),
                ('footer_blurb', models.TextField(default='Premium digital systems with a strong visual identity, built for trust, speed, and conversion.')),
                ('header_cta_label', models.CharField(default='Start a project', max_length=60)),
            ],
        ),
        migrations.CreateModel(
            name='TimelineStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('step_label', models.CharField(default='01', max_length=20)),
                ('title', models.CharField(max_length=120)),
                ('body', models.TextField()),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
            },
        ),
    ]
