# Generated by Django 6.0.3 on 2026-04-06 11:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0003_privacypage_termspage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GalleryMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='media/images/')),
                ('video', models.FileField(blank=True, upload_to='media/videos/')),
                ('order', models.PositiveIntegerField(default=0)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HomeCaseStudyMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='media/images/')),
                ('video', models.FileField(blank=True, upload_to='media/videos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('case_study', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='home.homecasestudy')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='PortfolioItemMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('media_type', models.CharField(choices=[('image', 'Image'), ('video', 'Video')], default='image', max_length=10)),
                ('title', models.CharField(blank=True, max_length=140)),
                ('caption', models.TextField(blank=True)),
                ('image', models.ImageField(blank=True, upload_to='media/images/')),
                ('video', models.FileField(blank=True, upload_to='media/videos/')),
                ('order', models.PositiveIntegerField(default=0)),
                ('portfolio_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='media_items', to='home.portfolioitem')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
