# Generated by assistant to add missing PortfolioItem text fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("home", "0005_portfolioitem_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="portfolioitem",
            name="process",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="testimonial",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name="portfolioitem",
            name="results",
            field=models.TextField(blank=True, default=""),
            preserve_default=False,
        ),
    ]
